navikt/pensjon-etterlatte

apps/etterlatte-node-server/package.json
apps/etterlatte-node-server/yarn.lock

Oppgraderer alle dependencies med unntak av node-fetch da den krever en større omskriving.

Upgrade etterlatte node server

---

apps/barnepensjon-ui/package.json
apps/barnepensjon-ui/yarn.lock

Bumper ds-react/css/icons til 2.5.1

---

apps/journalfoer-soeknad/src/main/kotlin/JournalfoerBarnepensjonSoeknadForDoffen.kt
apps/journalfoer-soeknad/src/main/kotlin/JournalfoerBarnepensjonSoeknadForPesys.kt
apps/journalfoer-soeknad/src/main/kotlin/JournalfoerSoeknad.kt
apps/journalfoer-soeknad/src/main/kotlin/JournalfoeringService.kt
apps/journalfoer-soeknad/src/main/kotlin/dokarkiv/JournalpostModel.kt
apps/journalfoer-soeknad/src/test/kotlin/JournalfoerBarnepensjonSoeknadForDoffenTest.kt
apps/journalfoer-soeknad/src/test/kotlin/JournalfoerBarnepensjonSoeknadForPesysTest.kt
apps/journalfoer-soeknad/src/test/kotlin/JournalfoerSoeknadTest.kt
apps/journalfoer-soeknad/src/test/kotlin/JournalfoeringServiceTest.kt

Ikke journalføre med behandlingstema på følgende saker: 
- Barnepensjon som skal behandles i Doffen.
- Alt av omstillingsstøenad.

EY-2105 Oppdatere behandlingstema for journalføring

---

apps/barnepensjon-ui/src/api/axios.ts
apps/etterlatte-node-server/src/auth/session.ts
apps/etterlatte-node-server/src/proxy.ts
apps/gjenlevendepensjon-ui/cypress/e2e/avbryt_soeknad.cy.js
apps/gjenlevendepensjon-ui/src/api/axios.ts
apps/omstillingsstoenad-ui/src/api/axios.ts

Backend: Sender 401 hvis token er undefined
Frontend: Laster inn siden på nytt ved 401 for å logge ut bruker.

Send 401 hvis token mangler og last inn siden på nytt

---

.github/workflows/.build-backend.yaml
.github/workflows/app-innsendt-soeknad.yaml
.github/workflows/app-journalfoer-soeknad.yaml
.github/workflows/app-selvbetjening-api.yaml
.github/workflows/app-sjekk-adressebeskyttelse.yaml
docker/backend.Dockerfile

Fint å komme opp på samme standard også her, særleg i og med at baseimaget vi bruker er særs utdatert.

EY-2827: Tilsvarande GHA-arbeidsflyt og Dockerfile som vi bruker i Gjenny

---

apps/barnepensjon-ui/cypress/e2e/navigaton_cancel.cy.ts
apps/barnepensjon-ui/src/components/application/about-parents/DeceasedParent.tsx
apps/barnepensjon-ui/src/components/application/about-parents/LivingParent.tsx
apps/barnepensjon-ui/src/components/application/your-situation/YourSituation.tsx
apps/barnepensjon-ui/src/context/language/LanguageContext.tsx
apps/etterlatte-node-server/src/server.ts
apps/gjenlevendepensjon-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/gjenlevendepensjon-ui/src/api/mapper/gjenlevendeMapper.ts
apps/gjenlevendepensjon-ui/src/components/soknad/1-omdeg/OmDeg.test.js
apps/gjenlevendepensjon-ui/src/components/soknad/3-avdod/OmDenAvdode.tsx
apps/gjenlevendepensjon-ui/src/hooks/useInnloggetBruker.test.js
apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/components/soknad/1-omdeg/OmDeg.test.js
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/OmDenAvdode.tsx
apps/omstillingsstoenad-ui/src/hooks/useInnloggetBruker.test.js

Rettar det aller meste frå https://github.com/navikt/pensjon-etterlatte/security/code-scanning

Rettar småting kodesjekken klagar på

---

apps/journalfoer-soeknad/.nais/dev.yaml

Dette siden Q1 inneholder prod-data og snart vil bli låst.

Journalføre på Q2 i stedet for Q1

---

apps/omstillingsstoenad-ui/src/components/felles/Navigasjon.tsx
apps/omstillingsstoenad-ui/src/components/felles/StyledComponents.tsx
apps/omstillingsstoenad-ui/src/components/felles/rhf/RHFInput.tsx
apps/omstillingsstoenad-ui/src/components/felles/rhf/RHFSelect.tsx
apps/omstillingsstoenad-ui/src/components/soknad/1-omdeg/__snapshots__/OmDeg.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/__snapshots__/OmDegOgAvdoed.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/__snapshots__/OmDenAvdode.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/__snapshots__/SituasjonenDin.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/fragmenter/AnnenSituasjon.tsx
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/fragmenter/ArbeidstakerInfokort.tsx
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/fragmenter/EtablererVirksomhet.tsx
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/fragmenter/SelvstendigInfokort.tsx
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/fragmenter/TilbudOmJobb.tsx
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/fragmenter/UnderUtdanning.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-inntekten-din/__snapshots__/InntektenDin.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/5-inntekten-din/fragmenter/EndringInntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-inntekten-din/fragmenter/Loennsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-inntekten-din/fragmenter/Naeringsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-inntekten-din/fragmenter/YtelserAndre.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-barn/__snapshots__/OpplysningerOmBarn.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/7-oppsummering/__snapshots__/Oppsummering.test.js.snap

- Setter mindre bredde på inputfelter under situasjonen din og inntekten din
- Lar bruker legge inn mellomrom på valutainput for la det være lettere å se tallet. 
- Endrer variant på tilbake, neste og avbryt til å følge retningslinjer fra aksel

Mindre endringer på situasjonen din og inntekten din

---

apps/omstillingsstoenad-ui/src/components/felles/Stegviser.tsx
apps/omstillingsstoenad-ui/src/components/soknad/SoknadDialog.tsx

Ny stegviser som fungerer både på mobil og desktop.
Gir også bedre oversikt over hvilke steg som er fullførte.
Lukket: 
Åpnet:

Ny stegviser

---

apps/barnepensjon-ui/src/components/application/about-parents/AboutParents.tsx
apps/barnepensjon-ui/src/locales/nb.ts

Fiks tekst for ukjent forelder alert

---

apps/omstillingsstoenad-ui/package.json
apps/omstillingsstoenad-ui/src/components/felles/__snapshots__/HvorforSpoerVi.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/1-omdeg/__snapshots__/OmDeg.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/__snapshots__/OmDegOgAvdoed.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/__snapshots__/OmDenAvdode.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/__snapshots__/SituasjonenDin.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/__snapshots__/MerOmSituasjonenDin.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/__snapshots__/InntektenDin.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/__snapshots__/Oppsummering.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/__snapshots__/SoknadKvittering.test.js.snap
apps/omstillingsstoenad-ui/src/utils/workers/WebWorker.ts
apps/omstillingsstoenad-ui/yarn.lock

Kjørt yarn upgrade og fikset feil som oppstod.

Kjør yarn upgrade på oms

---

apps/barnepensjon-ui/cypress/e2e/about_the_deceased.cy.ts
apps/barnepensjon-ui/src/api/dto/foreldreMapper.ts
apps/barnepensjon-ui/src/components/application/about-children/add-child/ParentQuestion.tsx
apps/barnepensjon-ui/src/components/application/about-parents/AboutParents.tsx
apps/barnepensjon-ui/src/components/application/summary/fragments/SummaryAboutChildren.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Verge skal ikke trenge å fylle inn for gjenlevende

---

apps/omstillingsstoenad-ui/src/api/mapper/fellesMapper.ts
apps/omstillingsstoenad-ui/src/api/mapper/gjenlevendeMapper.ts
apps/omstillingsstoenad-ui/src/components/felles/Datovelger.tsx
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/__snapshots__/OmDegOgAvdoed.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/forholdTilAvdoede/SamboerMedAvdoede.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Fikser feil mapping og feil tekst, samt viser om et felt er valgfritt

Fiks feil i mapping fra søknad - OMS

---

apps/barnepensjon-ui/src/components/FrontPage.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Ny forside barnepensjon

---

apps/barnepensjon-ui/cypress/util/constants.ts
apps/barnepensjon-ui/src/components/application/ReceiptPage.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Ny kvitteringside for barnepensjon

---

apps/omstillingsstoenad-ui/src/components/soknad/1-omdeg/__snapshots__/OmDeg.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/__snapshots__/MerOmSituasjonenDin.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/ArbeidstakerInfokort.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/SelvstendigInfokort.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/typer/bredde.ts

- Endrer Bredde.M til 35 for bedre tilpassing for mobil
- Fjerner (Valgfri) fra tekst da det settes i komponentene det gjelder

Mindre fixes - OMS

---

apps/omstillingsstoenad-ui/cypress/e2e/avbryt_soeknad.cy.js
apps/omstillingsstoenad-ui/cypress/e2e/fortsett_senere.cy.js
apps/omstillingsstoenad-ui/cypress/fixtures/kladd.json
apps/omstillingsstoenad-ui/src/components/soknad/FortsettSoeknadModal.tsx

Lastet litt random sider basert på kladd...

Fiks feil ved innlasting av steg

---

apps/omstillingsstoenad-ui/src/api/dto/FellesOpplysninger.ts
apps/omstillingsstoenad-ui/src/api/mapper/gjenlevendeMapper.ts
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/Loennsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/Naeringsinntekt.tsx
apps/omstillingsstoenad-ui/src/utils/dato.test.js
apps/omstillingsstoenad-ui/src/utils/dato.ts

Krever endring av common, som er her: https://github.com/navikt/pensjon-etterlatte-libs/pull/38
Dette vil fungere uten endring av common frem til 1. januar

Vis inntekt neste år når det er mellom oktober og desember

---

apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json
apps/omstillingsstoenad-ui/src/hooks/useLand.test.js
apps/omstillingsstoenad-ui/src/hooks/useLand.ts

Legg Norge på toppen av listen av land

---

.github/workflows/.build-backend.yaml
.github/workflows/.test-backend.yaml
.github/workflows/codeql.yml
.github/workflows/verify-branches.yaml
buildSrc/build.gradle.kts
docker/backend.Dockerfile

Vil påvirke utvikleroppsett:
Set projekt i idea til å bruke JDK 21 (temurin)
Set JAVA_HOME for terminal til JDK 21

Bump JDK til 21.x

---

apps/innsendt-soeknad/.nais/dev.yaml
apps/innsendt-soeknad/.nais/prod.yaml
apps/journalfoer-soeknad/.nais/dev.yaml
apps/journalfoer-soeknad/.nais/prod.yaml

Default `200m`.
- https://console.nav.cloud.nais.io/team/etterlatte/prod-gcp/app/innsendt-soeknad/utilization?from=2023-12-12&to=2023-12-19
- https://console.nav.cloud.nais.io/team/etterlatte/prod-gcp/app/journalfoer-soeknad/utilization?from=2023-12-12&to=2023-12-19

Redusert cpu for lytter-apps

---

apps/barnepensjon-ui/.nais/dev.yaml
apps/barnepensjon-ui/.nais/prod.yaml
apps/gjenlevendepensjon-ui/.nais/dev.yaml
apps/gjenlevendepensjon-ui/.nais/prod.yaml
apps/omstillingsstoenad-ui/.nais/dev.yaml
apps/omstillingsstoenad-ui/.nais/prod.yaml
apps/selvbetjening-api/.nais/dev.yaml
apps/selvbetjening-api/.nais/prod.yaml

Redusert requested resources

---

apps/barnepensjon-ui/.nais/dev.yaml
apps/barnepensjon-ui/.nais/prod.yaml
apps/gjenlevendepensjon-ui/.nais/dev.yaml
apps/gjenlevendepensjon-ui/.nais/prod.yaml
apps/omstillingsstoenad-ui/.nais/dev.yaml
apps/omstillingsstoenad-ui/.nais/prod.yaml

`unknown field "spec.idporten.clientUri"`
`unknown field "spec.idporten.accessTokenLifetime"`
`unknown field "spec.idporten.sidecar.errorPath"`
`unknown field "spec.idporten.postLogoutRedirectURIs"`
`unknown field "spec.idporten.frontchannelLogoutPath"`

EY-3297 Fjerne felter som får varsel om feil

---

apps/innsendt-soeknad/src/main/kotlin/Application.kt
apps/innsendt-soeknad/src/test/kotlin/soeknad/SoeknadRoutesIntegrationTest.kt
apps/selvbetjening-api/src/main/kotlin/ktortokenexchange/TokenSUpportSecurityMediator.kt
apps/selvbetjening-api/src/main/kotlin/ktortokenexchange/oauth/OAuth2Cache.kt
apps/selvbetjening-api/src/main/kotlin/ktortokenexchange/oauth/OAuth2Client.kt
gradle/libs.versions.toml

samt `etterlatte-libs`, pga samme bump der

Bump nav-token-support 3.2.0 -> 4.1.0

---

apps/barnepensjon-ui/src/components/application/about-children/add-child/AddChildToForm.tsx
apps/barnepensjon-ui/src/components/application/about-parents/DeceasedParent.tsx
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/OmDegOgAvdoed.tsx
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/__snapshots__/OmDegOgAvdoed.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/OmDenAvdode.tsx
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/__snapshots__/OmDenAvdode.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/SituasjonenDin.tsx
apps/omstillingsstoenad-ui/src/components/soknad/4-situasjonen-din/__snapshots__/SituasjonenDin.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/OpplysningerOmBarnepensjon.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/__snapshots__/OpplysningerOmBarn.test.js.snap

Lar det være på i dev for enklere å kunne fylle ut søknaden under utvikling.

Skru av Autocomplete for felter som ikke omhandler innlogget bruker

---

apps/barnepensjon-ui/src/components/FrontPage.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Bytter også ut \<ul> med ds-react sin List

Legg inn ny informasjon om personvern - BP

---

apps/omstillingsstoenad-ui/src/hooks/useInnloggetBruker.test.js
apps/omstillingsstoenad-ui/src/hooks/useInnloggetBruker.ts

Vil gjøre det samme på Barnepensjon når denne er godkjent.

Capitalize fornavn og etternavn

---

apps/omstillingsstoenad-ui/src/components/SideIkkeFunnet.tsx
apps/omstillingsstoenad-ui/src/components/dev/Admin.tsx
apps/omstillingsstoenad-ui/src/components/felles/Panel.tsx
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/nySivilstatus/SamboerSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/fragmenter/BoddEllerArbeidetUtland.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/__snapshots__/Oppsummering.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringBarnepensjon.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringInntektenDin.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringMerSituasjonenDin.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringOmDeg.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringOmDegOgAvdoed.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringOmDenAvdoede.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringSituasjonenDin.tsx

Panel fra ds-react fjernes ved neste major release og skal byttes ut med Box.
Dette fjerner da alle feilmeldinger i intellij

Bytter ut Panel med Box stylet som en Panel

---

apps/omstillingsstoenad-ui/src/components/felles/Stegviser.tsx

Fjerner stepper fra prod da den ikke er universelt utformet og en omskriving vil kreve større endringer. 
I Prod:
I Dev:

Visning av stepper skal kun være mulig i dev

---

apps/omstillingsstoenad-ui/src/components/soknad/1-omdeg/OmDeg.tsx
apps/omstillingsstoenad-ui/src/components/soknad/1-omdeg/__snapshots__/OmDeg.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/OmDenAvdode.tsx
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/__snapshots__/OmDenAvdode.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/fragmenter/BoddEllerArbeidetUtland.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/TilbudOmJobb.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/Loennsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/Naeringsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/PersonInfoOppsummering.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Mindre endringer over hele søknaden etter gjennomgang med Frida

EY-3349: Mindre forbedringer av søknad

---

gradle/libs.versions.toml

Trur ikkje den påverkar oss, men fint å ha det ute av verda
Sjå feks https://salsa.nav.cloud.nais.io/projects/8a2269c8-b3b7-4f2d-a9cd-5bd8e0d144c7/findings

Critical CVE i postgresql 42.7.1, så oppgraderer.

---

apps/barnepensjon-ui/src/components/application/about-you/AboutYou.tsx
apps/barnepensjon-ui/src/components/application/summary/fragments/SummaryAboutYou.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts
apps/barnepensjon-ui/src/utils/steps.ts

Legg til egen tittel på om deg for verge

---

apps/barnepensjon-ui/src/components/error/PageNotFound.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Oppdater 404 side for barnepensjon med nytt design

---

apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/api/dto/FellesOpplysninger.ts
apps/omstillingsstoenad-ui/src/api/mapper/gjenlevendeMapper.ts
apps/omstillingsstoenad-ui/src/api/mapper/typeMapper.ts
apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/PensjonEllerUfoere.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringInntektenDin.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/typer/inntekt.ts
gradle/libs.versions.toml

Krever oppdatering av common [(PR-64)](https://github.com/navikt/pensjon-etterlatte-libs/pull/64) og oppdatering av brev ([PR-214](https://github.com/navikt/pensjon-etterlatte-felles/pull/214))
Lager PR for oppdatering av common i saksbehandling når endringene av common er godkjent.

Legger til Pensjon utland som et eget valg

---

apps/innsendt-soeknad/.nais/dev.yaml
apps/innsendt-soeknad/.nais/prod.yaml
apps/innsendt-soeknad/src/main/kotlin/Application.kt
apps/innsendt-soeknad/src/main/kotlin/SoeknadPubliserer.kt
apps/innsendt-soeknad/src/main/kotlin/UtkastPubliserer.kt
apps/innsendt-soeknad/src/main/kotlin/jobs/PubliserTilstandJobb.kt
apps/innsendt-soeknad/src/main/kotlin/kafka/KafkaConfig.kt
apps/innsendt-soeknad/src/main/kotlin/kafka/KafkaProdusent.kt
apps/innsendt-soeknad/src/main/kotlin/soeknad/SoeknadDao.kt
apps/innsendt-soeknad/src/main/kotlin/soeknad/SoeknadModel.kt
apps/innsendt-soeknad/src/main/kotlin/soeknad/SoeknadService.kt
apps/innsendt-soeknad/src/test/kotlin/DatasourceBuilderTest.kt
apps/innsendt-soeknad/src/test/kotlin/SoeknadPublisererTest.kt
apps/innsendt-soeknad/src/test/kotlin/Utils.kt
apps/innsendt-soeknad/src/test/kotlin/UtkastPublisererTest.kt
apps/innsendt-soeknad/src/test/kotlin/soeknad/SoeknadDaoIntegrationTest.kt
apps/innsendt-soeknad/src/test/kotlin/soeknad/SoeknadRoutesIntegrationTest.kt
apps/innsendt-soeknad/src/test/kotlin/soeknad/SoeknadServiceTest.kt

Sender melding på kafka til min side for å vise at bruker har en søknad hen ikke er ferdig med. 
Sender melding for å slette utkastet hvis søknaden ferdigstilles, bruker vil slette utkastet eller når det har gått 72 timer.

EY-3544: Vis utkast til søknad på min side

---

apps/barnepensjon-ui/src/api/api.ts
apps/barnepensjon-ui/src/api/dto/foreldreMapper.ts
apps/barnepensjon-ui/src/api/dto/mapper.test.ts
apps/barnepensjon-ui/src/components/application/summary/fragments/SummaryAboutDeceasedParent.tsx
apps/barnepensjon-ui/src/components/application/the-deceased/DeceasedParentForm.tsx
apps/barnepensjon-ui/src/components/application/the-deceased/StaysAbroad.tsx
apps/barnepensjon-ui/src/components/common/rhf/RHFInput.tsx
apps/barnepensjon-ui/src/components/common/rhf/RHFSelect.tsx
apps/barnepensjon-ui/src/context/application/application.ts
apps/barnepensjon-ui/src/hooks/useCurrencies.ts
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Legg til valutavelger - BP

---

apps/omstillingsstoenad-ui/src/api/mapper/gjenlevendeMapper.ts

Det går nå ikke å sende inn søknad om OMS hvis man er student på heltid.

Ikke fyll ut studieprosent hvis studieform er heltid

---

apps/omstillingsstoenad-ui/src/components/felles/rhf/RHFInput.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/JevntOpptjentNaeringsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/YtelserAndre.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Mangler oversettelser, men koden kan ses gjennom.

EY-3658: Fortell søker at de kan skrive inn flere pensjonsordninger

---

apps/barnepensjon-ui/src/components/application/about-children/add-child/AddChildToForm.tsx
apps/barnepensjon-ui/src/components/application/about-children/add-child/IsGuardianQuestion.tsx
apps/barnepensjon-ui/src/locales/en.ts

Verge skal kunne søke om barnepensjon selv hvis hen trykker nei om de er verge.

EY-3704: La verge søke barnepensjon for hen ikke er verge for

---

apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json

Denne fiksen lar deg mocke søknaden for testing.

Oppdaterer dummy soeknad til å være lik faktisk datastruktur

---

gradle/libs.versions.toml

Spesielt for å få med https://github.com/navikt/pensjon-etterlatte-libs/pull/76

Ta i bruk nyeste versjon av libs common

---

.github/workflows/.build-backend.yaml
.github/workflows/.test-backend.yaml
.github/workflows/verify-branches.yaml
build.gradle.kts
buildSrc/akseptable-lisenser.json
gradle/libs.versions.toml

Lisenssjekk backend

---

apps/innsendt-soeknad/.nais/dev.yaml
apps/innsendt-soeknad/.nais/prod.yaml
apps/innsendt-soeknad/src/test/kotlin/DatasourceBuilderTest.kt
apps/innsendt-soeknad/src/test/kotlin/soeknad/SoeknadDaoIntegrationTest.kt
apps/innsendt-soeknad/src/test/kotlin/soeknad/SoeknadRoutesIntegrationTest.kt

obs: må endres i gcloud før merge
+ deploye vedlikeholdsbranch
https://github.com/navikt/pensjon-etterlatte/pull/1266

EY-3375 Bumpe til postgres 14

---

.github/dependabot.yml

Ref https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/

EY-4000: Grupperer oppdateringane for BP og OMS no som det er tilgjengeleg funksjonalitet i GitHub Actions

---

apps/omstillingsstoenad-ui/src/utils/translation.test.js

Ref https://github.com/navikt/pensjon-etterlatte/security/code-scanning/37

Tar bort import som ikkje blir brukt

---

apps/barnepensjon-ui/src/components/common/PersonInfo.tsx

Sikrer at statsborgerskap ikke kommer mellom fnr/fdato og advarselen som henger sammen med det.

Flytte statsborgerskap for å bedre alert for barnOver18

---

apps/barnepensjon-ui/src/App.tsx
apps/barnepensjon-ui/src/components/FrontPage.tsx
apps/barnepensjon-ui/src/components/application/about-children/AboutChildren.tsx
apps/barnepensjon-ui/src/components/application/about-children/ChildInfocard.tsx
apps/barnepensjon-ui/src/components/application/about-parents/ParentInfoCard.tsx
apps/barnepensjon-ui/src/components/application/summary/Summary.tsx
apps/barnepensjon-ui/src/components/common/Navigation.tsx
apps/barnepensjon-ui/src/components/common/PaymentDetails.tsx
apps/etterlatte-node-server/README.md
apps/etterlatte-node-server/package.json
apps/omstillingsstoenad-ui/src/App.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/__snapshots__/InntektenDin.test.jsx.snap
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/YtelserAndre.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/YtelserNAV.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/BarnInfokort.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/OpplysningerOmBarnepensjon.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/__snapshots__/OpplysningerOmBarn.test.jsx.snap

Øke tekststørrelse fra 16 til 18px som er standard for søknadder i NAV, også litt enklere kommando for å kjøre opp etterlatte-node-server

EY 3514 riktig teksstørrelse i søknad

---

apps/barnepensjon-ui/cypress/e2e/about_children.cy.ts
apps/barnepensjon-ui/src/components/application/about-children/ChildInfocard.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/BarnInfokort.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Ey 4077 varsel soekt barnepensjon

---

apps/barnepensjon-ui/cypress/e2e/navigaton_cancel.cy.ts
apps/barnepensjon-ui/cypress/e2e/navigaton_cancel_slett_soeknad.cy.ts
apps/barnepensjon-ui/cypress/e2e/summary_and_receipt.cy.ts
apps/barnepensjon-ui/src/components/application/summary/TextGroup.tsx
apps/barnepensjon-ui/src/utils/age.ts
apps/barnepensjon-ui/src/utils/date.ts
apps/barnepensjon-ui/src/utils/personalia.ts

Denne gjelder for både EY-4125 og EY-4127

Fiks utregning av legal age og formattering av dato i oppsummering

---

apps/barnepensjon-ui/src/components/FrontPage.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

EY-4174: Legg til tekst som ble fjernet

---

apps/barnepensjon-ui/src/components/application/the-deceased/DeceasedParentForm.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/OmDenAvdode.tsx
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/__snapshots__/OmDenAvdode.test.jsx.snap
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

EY-4194: Overskrift yrkesskade oms og bp

---

apps/barnepensjon-ui/cypress/e2e/about_children.cy.ts
apps/barnepensjon-ui/cypress/support/commands.ts
apps/barnepensjon-ui/cypress/util/constants.ts
apps/barnepensjon-ui/src/components/application/about-children/AboutChildren.tsx
apps/barnepensjon-ui/src/components/application/about-children/add-child/AddChildToForm.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Gjelder for både EY-4192 og EY-4193

Endringer for legg til barn

---

apps/barnepensjon-ui/cypress/e2e/about_children.cy.ts
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts
apps/etterlatte-node-server/src/mock/mock-api.ts

Feilmelding hvis man ikke har lagt til barn:
Feilmelding hvis man har lagt til barn, men ikke søkt om barnepensjon for dette barnet:

EY-4175: feilmelding legg til barn

---

apps/selvbetjening-backend/.nais/dev.yaml
apps/selvbetjening-backend/src/main/kotlin/Application.kt
apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/Inntektsjustering.kt
apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/InntektsjusteringRepository.kt
apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/InntektsjusteringRoutes.kt
apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/InntektsjusteringService.kt
apps/selvbetjening-backend/src/main/resources/db/migration/V1__initial_tables.sql
apps/selvbetjening-backend/src/test/kotlin/inntektsjustering/InntektsjusteringIntegrationTest.kt
apps/selvbetjening-backend/src/test/kotlin/inntektsjustering/InntektsjusteringRepositoryTest.kt
libs/utils/src/main/kotlin/no/nav/etterlatte/libs/utils/database/JdbcUtils.kt

Ny tabell, endepunkter og integrasjonstesting

Oppstart inntektsjustering

---

apps/barnepensjon-ui/src/components/common/Datepicker.tsx
apps/omstillingsstoenad-ui/src/components/felles/Datovelger.tsx

Fikser at man kan søke på ios og safari på macs.

Bruk standard new date som er støttet i Safari ios og

---

apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/Inntektsjustering.kt
apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/InntektsjusteringRepository.kt
apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/InntektsjusteringService.kt
apps/selvbetjening-backend/src/main/resources/db/migration/V2__inntektsaar_inntektsjustering.sql
gradle/libs.versions.toml

99% av PR er formatering fordi jeg hadde feil innstillinger i IntelliJ når jeg skrev disse klassene og repoet har ingen ktlint som redder meg 😢

Inntektsjustering bruk felles dto

---

apps/barnepensjon-ui/cypress/e2e/invalid_applicant.cy.ts
apps/barnepensjon-ui/src/components/error/InvalidApplicant.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Oppdater info hvis bruker er for ung

---

apps/barnepensjon-ui/src/components/application/about-children/add-child/AddChildToForm.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/OpplysningerOmBarnepensjon.tsx

Barn uten fnr, men med fødselsdato ble slettet hvis man prøvde og endre og deretter trykket avbryt.

Fiks at barn uten fnr blir slettet hvis man trykker avbryt

---

.husky/pre-commit
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/yarn.lock

pre-commit fungerte ikke da den ikke fant lint-staged. Har da byttet fra å kjøre det ved bruk av yarn til npx. Ser ut til å fungere for min del, men test gjerne selv.

Fiks husky for bp og oms

---

apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json
apps/omstillingsstoenad-ui/src/components/felles/Datovelger.tsx
apps/omstillingsstoenad-ui/src/components/felles/rhf/RHFInput.tsx
apps/omstillingsstoenad-ui/src/components/felles/rhf/RHFRadio.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/MerOmSituasjonenDin.test.jsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/__snapshots__/MerOmSituasjonenDin.test.jsx.snap
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/Arbeidstaker.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/ArbeidstakerInfokort.tsx

useFieldArray har problemer med conditional rendering, så bruker css for å skjule felter som ikke skal vises. 
Tar gjerne imot forslag hvis noen har andre ideer for løsning.

EY-4157: Alt slettes ved fjerning av ett element

---

apps/brukerdialog-sanity/sanity.config.ts
apps/brukerdialog-sanity/schemaTypes/index.ts
apps/brukerdialog-sanity/schemaTypes/inntektsjustering/index.ts
apps/etterlatte-node-server/src/config.ts

To forskjellige miljøer for dataen i sanity, da kan innholdsarbeiderne først teste endringene sine ved å se i dev-gcp, for å så kopiere det over til prod og publishe det der

EY-4426 flere sanity miljøer

---

apps/omstillingsstoenad-ui/src/components/soknad/SoknadForside.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Oppdater innledning for oms

---

apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/Oppsummering.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Gi feilmelding hvis bruker ikke har fyllt inn neste års inntekt

---

apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/BarnInfokort.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/__snapshots__/OpplysningerOmBarn.test.jsx.snap
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Økt mellomrom mellom knapper og tatt i bruk Aksel Button:
Oppdatert knapptekst for endring vs legge til ny

EY-4542: mellomrom mellom knapper legg til barn

---

apps/omstillingsstoenad-ui/.nais/dev.yaml

Midlertidig åpning for å kunne teste på mobil

Åpne oms soeknad eksternt i dev

---

apps/barnepensjon-ui/src/components/application/Dialogue.tsx

Vil gjøre samme for oms, men det blir i egen pr

EY-4558: Sett steps som interactive

---

apps/selvbetjening-backend/.nais/prod.yaml
apps/selvbetjening-ui/.nais/prod.yaml
apps/selvbetjening-ui/src/common/skjemaHeader/SkjemaHeader.tsx

EY-4666 Prodsette innmelding av inntekt for 2025!

---

apps/selvbetjening-ui/src/common/FantIkkeSiden.tsx
apps/selvbetjening-ui/src/common/IkkeGyldigForAaMeldeInnInntekt.tsx
apps/selvbetjening-ui/src/common/SystemUtilgjengelig.tsx
apps/selvbetjening-ui/src/common/innloggetInnbygger/InnloggetInnbyggerContext.tsx
apps/selvbetjening-ui/src/common/inntekt/ControlledInntektTextField.tsx
apps/selvbetjening-ui/src/inntektsjustering/1-innledning/InntektsjusteringInnledning.tsx
apps/selvbetjening-ui/src/inntektsjustering/2-inntekt-til-neste-aar/InntektsjusteringInntektTilNesteAar.tsx
apps/selvbetjening-ui/src/inntektsjustering/2-inntekt-til-neste-aar/SumAvOppgittInntekt.tsx
apps/selvbetjening-ui/src/inntektsjustering/2-inntekt-til-neste-aar/skjemaer/AttenTilSekstiEnAarSkjema.tsx
apps/selvbetjening-ui/src/inntektsjustering/2-inntekt-til-neste-aar/skjemaer/SekstiSyvAarSkjema.tsx
apps/selvbetjening-ui/src/inntektsjustering/2-inntekt-til-neste-aar/skjemaer/SekstiToTilSekstiSeksAarSkjema.tsx
apps/selvbetjening-ui/src/inntektsjustering/3-oppsummering/InntektsjusteringOppsummering.tsx
apps/selvbetjening-ui/src/inntektsjustering/4-kvittering/InntektsjusteringKvittering.tsx
apps/selvbetjening-ui/src/inntektsjustering/4-kvittering/index.css
apps/selvbetjening-ui/src/types/inntektsjustering.ts
apps/selvbetjening-ui/src/utils/inntekt.ts

Inkluderer:
- Litt fiksing av margins
- Bedre posisjon av footer
- Global sjekk om person ikke er gyldig for å sende inn inntekt basert på alder
- Spacing mellom tall når man oppgir inntekt

Brukervennlighet fikser i selvbetjening

---

apps/barnepensjon-ui/src/components/application/about-parents/DeceasedParent.tsx
apps/barnepensjon-ui/src/components/application/the-deceased/DeceasedParentForm.tsx
apps/barnepensjon-ui/src/hooks/useAmplitude.ts
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Samt legg til logging for å sjekke om hypotesen stemmer

EY-4593: Endre spørsmål om bodd og/eller arbeidet i utlandet

---

apps/barnepensjon-ui/package.json
apps/barnepensjon-ui/src/hooks/useAmplitude.ts
apps/barnepensjon-ui/yarn.lock
apps/omstillingsstoenad-ui/package.json
apps/omstillingsstoenad-ui/src/hooks/useAmplitude.ts
apps/omstillingsstoenad-ui/yarn.lock

Ref issue https://github.com/navikt/pensjon-etterlatte/issues/1594

Bytt ut amplitude klient

---

.husky/pre-commit
apps/selvbetjening-backend/.nais/dev.yaml
apps/selvbetjening-backend/.nais/prod.yaml
apps/selvbetjening-backend/src/main/kotlin/Application.kt
apps/selvbetjening-backend/src/main/kotlin/sak/HarOMSSakIGjennyResponse.kt
apps/selvbetjening-backend/src/main/kotlin/sak/SakKlient.kt
apps/selvbetjening-backend/src/main/kotlin/sak/SakRoute.kt
apps/selvbetjening-backend/src/main/kotlin/sak/SakService.kt
apps/selvbetjening-backend/src/main/resources/application.conf
apps/selvbetjening-ui/src/common/innloggetInnbygger/InnloggetInnbyggerContext.tsx

Neste bit blir å faktisk vise bruker hvis man ikke har sak

EY-4663 sjekke om innbygger har sak - delen for selvbetjening-backend

---

apps/selvbetjening-backend/.nais/dev.yaml
apps/selvbetjening-backend/.nais/prod.yaml
apps/selvbetjening-backend/build.gradle.kts
apps/selvbetjening-backend/src/main/kotlin/Application.kt
apps/selvbetjening-backend/src/main/kotlin/jobs/PubliserInntektsjusteringJobb.kt
apps/selvbetjening-backend/src/main/resources/application.conf
apps/selvbetjening-backend/src/test/kotlin/jobs/PubliserInntektsjusteringJobbTest.kt
gradle/libs.versions.toml
libs/etterlatte-funksjonsbrytere/build.gradle.kts
libs/etterlatte-funksjonsbrytere/src/main/kotlin/no/nav/etterlatte/funksjonsbrytere/FeatureToggleConfig.kt
libs/etterlatte-funksjonsbrytere/src/main/kotlin/no/nav/etterlatte/funksjonsbrytere/FeatureToggleService.kt
libs/etterlatte-funksjonsbrytere/src/testFixtures/kotlin/etterlatte/DummyFeatureToggleService.kt
settings.gradle.kts

Toggle for om lagrede inntektsjusteringer skal publiseres. Inkluderer også setup for feature toggles i pensjon-etterlatte

EY-4713 publiser inntektjusteringer feature toggle

---

apps/selvbetjening-ui/src/inntektsjustering/2-inntekt-til-neste-aar/SumAvOppgittInntekt.tsx

Sett formattering av total inntekt til nb for å unngå komma på engelsk

---

apps/etterlatte-node-server/package.json
apps/etterlatte-node-server/src/config.ts
apps/etterlatte-node-server/src/routers/unleashRouter.ts
apps/etterlatte-node-server/src/server.ts
apps/etterlatte-node-server/src/utils/unleash.ts
apps/etterlatte-node-server/yarn.lock
apps/selvbetjening-ui/.nais/dev.yaml
apps/selvbetjening-ui/.nais/prod.yaml
apps/selvbetjening-ui/src/main.tsx
apps/selvbetjening-ui/src/meldInnEndring/MeldInnEndringRoot.tsx
apps/selvbetjening-ui/src/meldInnEndring/meldInnEndringSkjema/MeldInnEndringSkjema.tsx

Merket at det plutselig ble veldig mye unleash greier i denne endringen. Tar derfor resten av unleash endringene som skjer i selvbetjening-ui i en annen PR

EY-4827 mvp skjema for å melde inn endringer

---

apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/api/dto/FellesOpplysninger.ts
apps/omstillingsstoenad-ui/src/api/mapper/fellesMapper.ts
apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringBarnepensjon.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/typer/person.ts
apps/omstillingsstoenad-ui/src/typer/utbetaling.ts

EY-4841: Fjern skattetrekk/forskuddstrekk fra OMS

---

apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/api/dto/FellesOpplysninger.ts
apps/omstillingsstoenad-ui/src/api/mapper/fellesMapper.ts
apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringBarnepensjon.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/typer/person.ts
apps/omstillingsstoenad-ui/src/typer/utbetaling.ts
gradle/libs.versions.toml
libs/utils/src/testFixtures/kotlin/etterlatte/SoeknadFixtures.kt

Tenker å legge inn oppdatert common her, men mangler godkjenning av https://github.com/navikt/pensjon-etterlatte-felles/pull/373

Fjern skattetrekk fra fixture

---

apps/barnepensjon-ui/src/components/application/ReceiptPage.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

EY-4878: Legg til info om skattetrekk på kvitteringsside for bokmål.

---

apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Oppdater tekst for søker om barnepensjon for dette barnet

---

apps/brukerdialog-sanity/schemaTypes/meldInnEndring/index.ts
apps/brukerdialog-sanity/schemaTypes/meldInnEndring/meldInnEndringKvitteringSchemaType.ts
apps/brukerdialog-sanity/schemaTypes/meldInnEndring/meldInnEndringOppsummeringSchemaType.ts
apps/etterlatte-node-server/src/mock/mock-selvbetjening-api.ts
apps/selvbetjening-backend/src/main/kotlin/omsmeldinnendring/OmsMeldInnEndringRepository.kt
apps/selvbetjening-backend/src/main/kotlin/omsmeldinnendring/OmsMeldInnEndringService.kt
apps/selvbetjening-backend/src/main/kotlin/omsmeldinnendring/OmsMeldInnEndringerRoute.kt
apps/selvbetjening-backend/src/main/resources/db/migration/V10__endre_struktur_oms_meldt_inn_endring.sql
apps/selvbetjening-ui/src/common/skjemaHeader/SkjemaHeader.tsx
apps/selvbetjening-ui/src/common/skjemaHeader/icons/FyllUtSkjemaIcon.tsx
apps/selvbetjening-ui/src/main.tsx
apps/selvbetjening-ui/src/meldInnEndring/3-oppsummering/FeilIOppretelseAvEndring.tsx
apps/selvbetjening-ui/src/meldInnEndring/3-oppsummering/MeldInnEndringOppsummering.tsx
apps/selvbetjening-ui/src/meldInnEndring/4-kvittering/MeldInnEndringKvittering.tsx
apps/selvbetjening-ui/src/meldInnEndring/4-kvittering/index.css
apps/selvbetjening-ui/src/meldInnEndring/sanity.types.ts

Ey 4953 kvittering for meldt inn endring

---

apps/barnepensjon-ui/src/components/application/the-deceased/StaysAbroad.tsx

Oppdater design til å være likt OMS

---

README.md
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/README.md
apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts

Den store NAVneendringen
Har ikke rørt selvbetjening siden jeg ikke er helt sikker på hva som er generert av cypress og ikke

Bytt NAV til Nav

---

apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/PensjonEllerUfoere.tsx

OMS - Bruke text area i tjenestepensjon for å kunne skrive flere samtidig

---

apps/omstillingsstoenad-ui/cypress/fixtures/featureToggles.json
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/InntektenDin.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/InntektFremTilDoedsallet.tsx
apps/omstillingsstoenad-ui/src/typer/inntekt.ts

EY-5280 inntekt frem til doedsfallet

---

apps/omstillingsstoenad-ui/src/components/felles/Maanedvelger.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/InntektenDin.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/SkalGaaAvMedAlderspensjon.tsx
apps/omstillingsstoenad-ui/src/typer/inntekt.ts

EY-5292 spørsmål om alderspensjon
