apps/journalfoer-soeknad/src/main/kotlin/AppBuilder.kt

P.t. vil appen potensielt journalføre bytearray som ikke er en pdf. 
Eksempelvis hvis pdfgen feiler vil ikke feilen fanges opp, og siden så og si _alt_ er en bytearray, regner appen responsen som OK. Kan dermed ende opp med å journalføre en feilmelding som "pdf"...

Sette expectSuccess til true for å sikre pdfgen

---

apps/etterlatte-node-server/Dockerfile
docker/frontend.Dockerfile

Det inneheld mykje meir enn vi treng, og er også sårbart.
snyk har ein god post på https://snyk.io/blog/choosing-the-best-node-js-docker-image/ , følgjer rådet derifrå og byttar over til bookworm-slim-varianten, som er eit fullverdig node-miljø og ikkje så mykje meir.
Veldig mange sårbarheiter dependency track rapporterer om kjem frå node-baseimaget: https://console.nav.cloud.nais.io/team/etterlatte/vulnerabilities

Det er unødvendig og sårbart å bruke fullsize-node-baseimaget

---

apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/api/dto/FellesOpplysninger.ts
apps/omstillingsstoenad-ui/src/api/mapper/gjenlevendeMapper.ts
apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/Loennsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/Naeringsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/6-inntekten-din/fragmenter/SesongbasertNaeringsinntekt.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/Oppsummering.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringInntektenDin.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/typer/inntekt.ts
apps/omstillingsstoenad-ui/src/utils/dato.test.js
apps/omstillingsstoenad-ui/src/utils/dato.ts

Mangler følgende fra andre repoer:

Vis egne felter for inntekt i norge hvis dødsfall var året før

---

apps/barnepensjon-ui/src/hooks/useLoggedInUser.ts
apps/barnepensjon-ui/src/utils/capitalize.test.ts
apps/barnepensjon-ui/src/utils/capitalize.ts
apps/omstillingsstoenad-ui/src/hooks/useInnloggetBruker.test.js
apps/omstillingsstoenad-ui/src/hooks/useInnloggetBruker.ts
apps/omstillingsstoenad-ui/src/utils/capitalize.test.ts
apps/omstillingsstoenad-ui/src/utils/capitalize.ts

Navn er nå capitalized istedenfor uppercase
Enkelt navn
Dobbeltnavn med -

Capitalize fornavn og etternavn for BP. Fikser skrivefeil i OMS

---

apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/EtablererVirksomhet.tsx

Feltet er valgfritt når checkbox er krysset av
Feltet er ikke valgfritt når checkbox ikke er krysset av

Fikser feil i logikk ved valgfri orgnr

---

.github/workflows/.build-frontend.yaml

Sjå feks https://github.com/navikt/pensjon-etterlatte/actions/runs/8263863962/job/22606212404
> Cache restored successfully
> Cache restored from key: etterlatte-node-server-

Fiksar yarn-lock-hash-mekanismne, set-output er visst ikkje støtta lenger

---

apps/gjenlevendepensjon-ui/src/App.test.js
apps/gjenlevendepensjon-ui/src/App.tsx
apps/gjenlevendepensjon-ui/src/components/SoeknadUgyldig.tsx

Gi søker beskjed om at GJP ikke lenger er mulig å søke på etter 1. april 2024

EY-3671: Send søker fra gjp til oms fra 1. april

---

apps/omstillingsstoenad-ui/src/api/mapper/fellesMapper.ts
apps/omstillingsstoenad-ui/src/api/mapper/soeknadMapper.ts
apps/omstillingsstoenad-ui/src/components/soknad/1-omdeg/utenlandskBankInfo/UtenlandskBankInfo.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/__snapshots__/OpplysningerOmBarn.test.js.snap
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringBarnepensjon.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/typer/person.ts

- Ikke vis skattetrekk hvis utenlandsk konto er valgt
Legge til norsk kontonummer på barnet -> La bruker velge om de ønsker skattetrekk
Legge til utenlandsk kontonummer på barnet -> Ikke la bruker velge ønske skattetrekk
Hvis gjenlevende har norsk kontonummer -> La bruker velge om de ønsker skattetrekk
Hvis gjenlevende har utenlandsk kontonummer -> Ikke la bruker velge ønske skattetrekk

EY-3720: Legg til utbetalingsinformasjon for utenlandsk konto på barnepensjon

---

apps/journalfoer-soeknad/src/main/kotlin/dokarkiv/DokarkivKlient.kt
apps/journalfoer-soeknad/src/test/kotlin/dokarkiv/DokarkivKlientTest.kt

Dette skjer som oftest fordi første kall mot dokarkiv ikke har gitt respons. I siste tilfelle fikk første kall timeout, men journalposten ble lagret. Når riveren forsøker på nytt kastes det feil. Dette er litt unødvendig. 
Dokarkiv returnerer samme respons på 200 og 409, så det ryddigste er å bare logge warning og journalpostId på dokumentet det gjelder. 
https://dokarkiv.dev.intern.nav.no/swagger-ui/index.html#/journalpostapi/opprettJournalpost

Hotfix: Ikke kaste feil ved 409 (duplikat journalpost)

---

gradle/libs.versions.toml

Denne rapids and rivers-versjonen byrjar å bli gamal, og bruker ein sårbar versjon av kafka-clients, så det er på tide å oppgradere

Oppgraderer rapids and rivers

---

apps/barnepensjon-ui/package.json
apps/barnepensjon-ui/yarn.lock
apps/omstillingsstoenad-ui/package.json
apps/omstillingsstoenad-ui/yarn.lock

Ref https://salsa.nav.cloud.nais.io/projects/557cd60d-8205-4ac1-89c1-5c531564fb68/findings og https://salsa.nav.cloud.nais.io/projects/3e994583-a9ce-4d23-bf0d-df92a243470d/findings

EY-3963: dependencygraph klager på at braces-biblioteket i versjon 3.0.2 er sårbart, så oppgraderer

---

apps/barnepensjon-ui/package.json
apps/etterlatte-node-server/package.json
apps/omstillingsstoenad-ui/package.json

Verifisert i dependencytrack at braces 3.0.2, som ga åtvaringar tidlegare, no ikkje gjer det: https://salsa.nav.cloud.nais.io/projects/947307e1-31d9-4282-a3d2-4900678e5478/findings

Rettar syntaks i braces-versjonslåsinga

---

apps/omstillingsstoenad-ui/src/components/felles/Panel.tsx
apps/omstillingsstoenad-ui/src/components/soknad/2-omdegogavdoed/nySivilstatus/SamboerSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/3-avdod/fragmenter/BoddEllerArbeidetUtland.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/__snapshots__/MerOmSituasjonenDin.test.jsx.snap
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/Arbeidstaker.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/ArbeidstakerInfokort.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/Selvstendig.tsx
apps/omstillingsstoenad-ui/src/components/soknad/5-mer-om-situasjonen-din/fragmenter/SelvstendigInfokort.tsx
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx

Gjenbruker designet til fyllut
Bodd eller arbeidet i utlandet
Samboer (Denne fikk samme design da den var lik de andre før)
Arbeidstaker
Selvstendig næringsdrivende

EY-4156: Tydligere visning av hva hvilke felter som slettes

---

apps/barnepensjon-ui/src/components/common/PaymentDetails.tsx

Hvis bruker nå velger kroner, så kan man kun legge inn 2 tall. Så bytter til numberinput for at bruker skal kunne legge inn mer enn 99,- i skattetrekk.

EY-4668: Bytt til numberinput for skattetrekk

---

apps/barnepensjon-ui/src/components/application/summary/Summary.tsx
apps/barnepensjon-ui/src/components/error/SystemUnavailable.tsx
apps/barnepensjon-ui/src/hooks/useAmplitude.ts
apps/omstillingsstoenad-ui/src/hooks/useAmplitude.ts

så gjør det påkrevd for å alltid ha med det man får gratis fra Amplitude

logEvent uten eventdata tar ikke med innebygd Amplitude logging,

---

apps/barnepensjon-ui/src/hooks/useAmplitude.ts
apps/omstillingsstoenad-ui/src/hooks/useAmplitude.ts
apps/selvbetjening-ui/src/hooks/useAmplitude.ts

Custom events sliter med å bli fanger opp, så må bruke api key istedenfor default. 
Ref: https://nav-it.slack.com/archives/CMK1SCBP1/p1732179998529649

Ny api key amplitude

---

apps/etterlatte-node-server/package.json
apps/selvbetjening-ui/.nais/dev.yaml
apps/selvbetjening-ui/.nais/prod.yaml
apps/selvbetjening-ui/cypress/e2e/spec.cy.js
apps/selvbetjening-ui/package.json
apps/selvbetjening-ui/src/inntektsjustering/InntektjusteringRoot.tsx
apps/selvbetjening-ui/src/meldInnEndring/MeldInnEndringRoot.tsx

Var litt issues med ingressen når jeg satt den til å være www.nav.no/omstillingsstonad. Som f.eks at produktsiden ble overridet.
Når har skjemaene i selvbetjening fått ingressen www.nav.no/omstillingsstonad/skjema

Legg til skjema som path for selvbetjening

---

apps/selvbetjening-backend/src/main/kotlin/jobs/PubliserInntektsjusteringJobb.kt

1. Endret til å hendte alle som tidligere har status sendt før nye sendes slik at de ikke sendes på nytt med en gang
2. Midlertidig bryter for å kunne sende en inntektsendring av gangen for å verifiser ei prod

Inntektsendring proeve sendte foerst

---

apps/barnepensjon-ui/cypress/support/commands.ts
apps/barnepensjon-ui/src/api/dto/FellesOpplysninger.ts
apps/barnepensjon-ui/src/api/dto/mapper.test.ts
apps/barnepensjon-ui/src/api/dto/soeknadMapper.ts
apps/barnepensjon-ui/src/assets/mocks/mock-child-single-dead.json
apps/barnepensjon-ui/src/assets/mocks/mock-child.json
apps/barnepensjon-ui/src/assets/mocks/mock-guardian.json
apps/barnepensjon-ui/src/assets/mocks/mock-parent.json
apps/barnepensjon-ui/src/components/application/summary/fragments/PaymentDetailsSummary.tsx
apps/barnepensjon-ui/src/components/common/PaymentDetails.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts
apps/barnepensjon-ui/src/types/person.ts
apps/omstillingsstoenad-ui/cypress/e2e/enkel_soeknadsflyt.cy.js
apps/omstillingsstoenad-ui/src/api/dto/FellesOpplysninger.ts
apps/omstillingsstoenad-ui/src/api/mapper/fellesMapper.ts
apps/omstillingsstoenad-ui/src/assets/dummy-soeknad.json
apps/omstillingsstoenad-ui/src/components/soknad/7-barnepensjon/LeggTilBarnSkjema.tsx
apps/omstillingsstoenad-ui/src/components/soknad/8-oppsummering/fragmenter/OppsummeringBarnepensjon.tsx
apps/omstillingsstoenad-ui/src/locales/en.ts
apps/omstillingsstoenad-ui/src/locales/nb.ts
apps/omstillingsstoenad-ui/src/locales/nn.ts
apps/omstillingsstoenad-ui/src/typer/person.ts
apps/omstillingsstoenad-ui/src/typer/utbetaling.ts
apps/selvbetjening-backend/src/main/kotlin/inntektsjustering/InntektsjusteringRepository.kt
apps/selvbetjening-backend/src/test/kotlin/jobs/PubliserInntektsjusteringJobbTest.kt
gradle/libs.versions.toml
libs/utils/src/testFixtures/kotlin/etterlatte/SoeknadFixtures.kt

Første del av fjerning av frivillig skattetrekk. Splitter opp alle steg i egne PR for å unngå at det blir en gigantisk en. 
Denne omhandler da fjerning av frivillig skattetrekk fra søknaden til barnepensjon
Det som mangler

EY-4841: Fjern frivillig skattetrekk

---

apps/barnepensjon-ui/src/components/application/about-children/ChildInfocard.tsx
apps/barnepensjon-ui/src/components/application/about-children/add-child/AddChildToForm.tsx
apps/barnepensjon-ui/src/components/application/about-parents/ParentInfoCard.tsx
apps/barnepensjon-ui/src/components/common/card/InfoCard.tsx
apps/barnepensjon-ui/src/locales/en.ts
apps/barnepensjon-ui/src/locales/nb.ts
apps/barnepensjon-ui/src/locales/nn.ts

Endre og fjerne barn har nå større mellomrom og er faktiske knapper.
Lagre endring hvis man endrer ting på et barn
Fortsatt legg til hvis man legger til nytt barn

EY-4858: Oppdater knapper legg til barn

---

apps/barnepensjon-ui/README.md
apps/barnepensjon-ui/package.json
apps/barnepensjon-ui/yarn.lock
apps/omstillingsstoenad-ui/README.md
apps/omstillingsstoenad-ui/package.json
apps/omstillingsstoenad-ui/yarn.lock
apps/selvbetjening-ui/README.md
apps/selvbetjening-ui/package.json
apps/selvbetjening-ui/yarn.lock

Ved hjelp av `concurrently` så kjøres frontend og etterlatte node server med riktig path når man bruker `yarn dev`.
Man slipper da å kjøre opp 2 apper hver gang man skal jobbe med søknad og vi tar i bruk yarn dev slik at det blir felles på tvers av saksbehandling og søknadene.

Kjør frontend og node server ved bruk av yarn dev
